// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID                int64          `json:"id"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	Fname             string         `json:"fname"`
	Lname             string         `json:"lname"`
	Sex               sql.NullString `json:"sex"`
	Dob               sql.NullTime   `json:"dob"`
	Phone             sql.NullString `json:"phone"`
	Email             sql.NullString `json:"email"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
}
