// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, username string) error
	GetCustomer(ctx context.Context, username string) (Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	UpdateInfoCustomer(ctx context.Context, arg UpdateInfoCustomerParams) (Customer, error)
	UpdatePasswordCustomer(ctx context.Context, arg UpdatePasswordCustomerParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
